# Clock signal
set_property PACKAGE_PIN W5 [get_ports clock_100MHz]
    set_property IOSTANDARD LVCMOS33 [get_ports clock_100MHz]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets counterr/counter_ch_reg[2]_i_2_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets counterr/counter_ch_reg[7]_i_4_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets counterr/counter_ch_reg[3]_i_2_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets counterr/counter_ch_reg[7]_i_3_n_0]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets counterr/counter_p_0_in[2]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets counterr/p_0_in[3]]

#pushbuttons
set_property PACKAGE_PIN U18 [get_ports pushbuttons[4]]
    set_property IOSTANDARD LVCMOS33 [get_ports pushbuttons[4]]
set_property PACKAGE_PIN T18 [get_ports pushbuttons[3]]
    set_property IOSTANDARD LVCMOS33 [get_ports pushbuttons[3]]
set_property PACKAGE_PIN W19 [get_ports pushbuttons[2]]
    set_property IOSTANDARD LVCMOS33 [get_ports pushbuttons[2]]
set_property PACKAGE_PIN T17 [get_ports pushbuttons[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports pushbuttons[1]]
set_property PACKAGE_PIN U17 [get_ports pushbuttons[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports pushbuttons[0]]

#7 segment display
set_property PACKAGE_PIN W7 [get_ports {LEDout[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[6]}]
set_property PACKAGE_PIN W6 [get_ports {LEDout[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[5]}]
set_property PACKAGE_PIN U8 [get_ports {LEDout[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[4]}]
set_property PACKAGE_PIN V8 [get_ports {LEDout[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[3]}]
set_property PACKAGE_PIN U5 [get_ports {LEDout[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[2]}]
set_property PACKAGE_PIN V5 [get_ports {LEDout[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[1]}]
set_property PACKAGE_PIN U7 [get_ports {LEDout[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[0]}]
    
set_property PACKAGE_PIN U2 [get_ports {anode_activate[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode_activate[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode_activate[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode_activate[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[3]}]