# Clock signal
set_property PACKAGE_PIN W5 [get_ports clock_100MHz]
    set_property IOSTANDARD LVCMOS33 [get_ports clock_100MHz]

# Switches
set_property PACKAGE_PIN V17 [get_ports {switch_input[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[0]}]
set_property PACKAGE_PIN V16 [get_ports {switch_input[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[1]}]
set_property PACKAGE_PIN W16 [get_ports {switch_input[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[2]}]
set_property PACKAGE_PIN W17 [get_ports {switch_input[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[3]}]
set_property PACKAGE_PIN W15 [get_ports {switch_input[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[4]}]
set_property PACKAGE_PIN V15 [get_ports {switch_input[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[5]}]

set_property PACKAGE_PIN U1 [get_ports {switch_input[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[6]}]
set_property PACKAGE_PIN T1 [get_ports {switch_input[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[7]}]
set_property PACKAGE_PIN R2 [get_ports {switch_input[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {switch_input[8]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDs[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN U15 [get_ports {LEDs[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[5]}]

set_property PACKAGE_PIN V13 [get_ports {LEDs[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[6]}]

set_property PACKAGE_PIN N3 [get_ports {LEDs[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[7]}]
set_property PACKAGE_PIN P1 [get_ports {LEDs[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[8]}]
set_property PACKAGE_PIN L1 [get_ports {LEDs[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[9]}]

#7 segment display
set_property PACKAGE_PIN W7 [get_ports {LEDout[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[6]}]
set_property PACKAGE_PIN W6 [get_ports {LEDout[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[5]}]
set_property PACKAGE_PIN U8 [get_ports {LEDout[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[4]}]
set_property PACKAGE_PIN V8 [get_ports {LEDout[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[3]}]
set_property PACKAGE_PIN U5 [get_ports {LEDout[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[2]}]
set_property PACKAGE_PIN V5 [get_ports {LEDout[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[1]}]
set_property PACKAGE_PIN U7 [get_ports {LEDout[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDout[0]}]
    
set_property PACKAGE_PIN U2 [get_ports {anode_activate[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode_activate[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode_activate[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode_activate[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode_activate[3]}]
